# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Deep Learning Experience
url: http://andrewhuman.github.io
feed: /atom.xml
author_info: <a href="http://andrewhuman.github.io/">andrewhuman</a>

myblog:
  gavatar: images/avatar.png
  gpname: andrewhuman
  linkedin: http://www.linkedin.com/in/andrewhuman
  github: https://github.com/andrewhuman
  email: mailto:huyouni174@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
